services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./flask-app:/app
    depends_on:
      - mongo-service
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo-service:27017/todo
    restart: always
  
  mongo-service:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: