services:
  web:
    image: tejeshunyu/flask-todo-app:v1
    ports:
      - "5001:5000"
    volumes:
      - ./flask-app:/app
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/todo
    restart: always
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: