apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-app-rc
spec:
  replicas: 3
  selector:
    app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: tejeshunyu/flask-todo-app:v1
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        env:
        - name: MONGO_HOST
          value: "mongo"
        - name: MONGO_PORT
          value: "27017"